<a href="https://colab.research.google.com/github/cromcruach52/Pandas-Numpy-References/blob/main/Module_3_and_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Loading

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('WineQT.csv')

In [ ]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

# Data Exploration

In [ ]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1143.000000       1143.000000  1143.000000     1143.000000   
mean        8.311111          0.531339     0.268364        2.532152   
std         1.747595          0.179633     0.196686        1.355917   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.392500     0.090000        1.900000   
50%         7.900000          0.520000     0.250000        2.200000   
75%         9.100000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1143.000000          1143.000000           1143.000000  1143.000000   
mean      0.086933            15.615486             45.914698     0.996730   
std       0.047267            10.250486             32.782130     0.001925   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             21.000000     0.995570   
50%       0.079000            13.000000             37.000000     0.996680   
75%       0.090000            21.000000             61.000000     0.997845   
max       0.611000            68.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality           Id  
count  1143.000000  1143.000000  1143.000000  1143.000000  1143.000000  
mean      3.311015     0.657708    10.442111     5.657043   804.969379  
std       0.156664     0.170399     1.082196     0.805824   463.997116  
min       2.740000     0.330000     8.400000     3.000000     0.000000  
25%       3.205000     0.550000     9.500000     5.000000   411.000000  
50%       3.310000     0.620000    10.200000     6.000000   794.000000  
75%       3.400000     0.730000    11.100000     6.000000  1209.500000  
max       4.010000     2.000000    14.900000     8.000000  1597.000000

In [ ]:
print(df.describe())

       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1143.000000       1143.000000  1143.000000     1143.000000   
mean        8.311111          0.531339     0.268364        2.532152   
std         1.747595          0.179633     0.196686        1.355917   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.392500     0.090000        1.900000   
50%         7.900000          0.520000     0.250000        2.200000   
75%         9.100000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1143.000000          1143.000000           1143.000000  1143.000000   
mean      0.086933            15.615486             45.914698     0.996730   
std       0.047267            10.250486             32.782130     0.001925   
min       0.012000             1.000000         

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64  
 12  Id                    1143 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 116.2 KB


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64  
 12  Id                    1143 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 116.2 KB
None


# CHecking and Handling Missing Data

In [ ]:
df.shape

(1143, 13)

In [ ]:
df_cleaned = df.dropna()

In [ ]:
df_cleaned.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            6.7              0.58         0.08             1.8      0.097   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 15.0                  65.0   0.9959  3.28       0.54   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9.8        5   2  
3      9.8        6   3  
4      9.4        5   4  
5      9.4        5   5  
6      9.4        5   6  
7     10.0        7   7  
8      9.5        7   8  
9      9.2        5  10

In [ ]:
df_inputed = df.fillna(df.mean)

In [ ]:
df_inputed.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            6.7              0.58         0.08             1.8      0.097   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 15.0                  65.0   0.9959  3.28       0.54   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9.8        5   2  
3      9.8        6   3  
4      9.4        5   4  
5      9.4        5   5  
6      9.4        5   6  
7     10.0        7   7  
8      9.5        7   8  
9      9.2        5  10

fillna and dropna are just for cleaning data

# Filtering and Selecting Data

In [ ]:
selected_col = df[['fixed acidity', 'volatile acidity']]

In [ ]:
selected_col

fixed acidity  volatile acidity
0               7.4             0.700
1               7.8             0.880
2               7.8             0.760
3              11.2             0.280
4               7.4             0.700
...             ...               ...
1138            6.3             0.510
1139            6.8             0.620
1140            6.2             0.600
1141            5.9             0.550
1142            5.9             0.645

[1143 rows x 2 columns]

In [ ]:
filter_col = df[df['quality'] > 5]

In [ ]:
filter_col

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3              11.2              0.28         0.56             1.9      0.075   
7               7.3              0.65         0.00             1.2      0.065   
8               7.8              0.58         0.02             2.0      0.073   
12              8.5              0.28         0.56             1.8      0.092   
13              7.9              0.32         0.51             1.8      0.341   
...             ...               ...          ...             ...        ...   
1136            6.3              0.55         0.15             1.8      0.077   
1137            5.4              0.74         0.09             1.7      0.089   
1138            6.3              0.51         0.13             2.3      0.076   
1139            6.8              0.62         0.08             1.9      0.068   
1141            5.9              0.55         0.10             2.2      0.062   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3                    17.0                  60.0  0.99800  3.16       0.58   
7                    15.0                  21.0  0.99460  3.39       0.47   
8                     9.0                  18.0  0.99680  3.36       0.57   
12                   35.0                 103.0  0.99690  3.30       0.75   
13                   17.0                  56.0  0.99690  3.04       1.08   
...                   ...                   ...      ...   ...        ...   
1136                 26.0                  35.0  0.99314  3.32       0.82   
1137                 16.0                  26.0  0.99402  3.67       0.56   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1141                 39.0                  51.0  0.99512  3.52       0.76   

      alcohol  quality    Id  
3         9.8        6     3  
7        10.0        7     7  
8         9.5        7     8  
12       10.5        7    16  
13        9.2        6    19  
...       ...      ...   ...  
1136     11.6        6  1590  
1137     11.6        6  1591  
1138     11.0        6  1592  
1139      9.5        6  1593  
1141     11.2        6  1595  

[621 rows x 13 columns]

In [ ]:
filter_col2 = df[df['quality'] > 3]

In [ ]:
filter_col2

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1137 rows x 13 columns]

In [ ]:
filter_col3 = df[df['quality'] < 5]

In [ ]:
filter_col3

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
29              8.8             0.610         0.30             2.8      0.088   
32              4.6             0.520         0.15             2.1      0.054   
50              8.3             0.675         0.26             2.1      0.084   
54              8.3             0.625         0.20             1.5      0.080   
66              5.0             1.020         0.04             1.4      0.045   
103             9.2             0.520         1.00             3.4      0.610   
112             7.6             0.680         0.02             1.3      0.072   
118             7.3             0.550         0.03             1.6      0.072   
120             7.9             0.885         0.03             1.8      0.058   
142             6.9             1.090         0.06             2.1      0.061   
185             7.0             0.975         0.04             2.0      0.087   
189             8.1             0.870         0.00             3.3      0.096   
284            12.5             0.460         0.49             4.5      0.070   
324            11.6             0.580         0.66             2.2      0.074   
368            10.4             0.610         0.49             2.1      0.200   
411             9.9             0.500         0.24             2.3      0.103   
449            10.1             0.935         0.22             3.4      0.105   
458             8.3             0.845         0.01             2.2      0.070   
500             7.5             0.380         0.48             2.6      0.073   
501             9.1             0.765         0.04             1.6      0.078   
585             6.9             0.390         0.24             2.1      0.102   
594             7.5             0.685         0.07             2.5      0.058   
596            11.6             0.470         0.44             1.6      0.147   
618             7.3             0.350         0.24             2.0      0.067   
656             8.4             0.670         0.19             2.2      0.093   
832             6.5             0.880         0.03             5.6      0.079   
839             8.8             0.955         0.05             1.8      0.075   
876             8.1             0.730         0.00             2.5      0.081   
877             6.5             0.670         0.00             4.3      0.057   
891             6.3             1.020         0.00             2.0      0.083   
904             8.5             0.400         0.40             6.3      0.050   
922             7.6             1.580         0.00             2.1      0.137   
1015            6.4             0.530         0.09             3.9      0.123   
1040            6.2             0.785         0.00             2.1      0.060   
1044            6.7             1.040         0.08             2.3      0.067   
1046            7.3             0.980         0.05             2.1      0.061   
1055            7.1             0.875         0.05             5.7      0.082   
1057            5.6             0.620         0.03             1.5      0.080   
1074            6.7             0.760         0.02             1.8      0.078   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
29                   17.0                  46.0  0.99760  3.26       0.51   
32                    8.0                  65.0  0.99340  3.90       0.56   
50                   11.0                  43.0  0.99760  3.31       0.53   
54                   27.0                 119.0  0.99720  3.16       1.12   
66                   41.0                  85.0  0.99380  3.75       0.48   
103                  32.0                  69.0  0.99960  2.74       2.00   
112                   9.0                  20.0  0.99650  3.17       1.08   
118                  17.0                  42.0  0.99560  3.37       0.48   
120                   4.0                   8.0  0.99720  3.36       0.3

# Data Transformation

# Merging and Concatenating DartaFrames

In [ ]:
df3 = pd.DataFrame({('ID'):[1, 2], 'Name':['Jiro', 'Clark']})

In [ ]:
df4 = pd.DataFrame({('ID'):[3, 4], 'Name':['Jester', 'Hans']})

In [ ]:
df3

ID   Name
0   1  Alice
1   2    Bob

In [ ]:
df4

ID    Name
0   3  Jester
1   4    Hans

In [ ]:
df_c = pd.concat([df3, df4], axis = 0)

In [ ]:
df_c

ID    Name
0   1   Alice
1   2     Bob
0   3  Jester
1   4    Hans

In [ ]:
df_m = pd.merge(df3, df4, on = 'ID')

In [ ]:
df_m

Empty DataFrame
Columns: [ID, Name_x, Name_y]
Index: []

# Handling Duplicates

# Exporting Data

In [ ]:
filter_col.to_csv('cleaned.csv', index = False)

In [ ]:
filter_col2.to_csv('cleaned2.csv', index = False)

# Module 4 NumPy

In [ ]:
# Meaning of Py, it provides support for large, multi0dimesional arrays and matrices, along with a collection of high-levelmathematical functions to operate on these arrays.

In [ ]:
import numpy as np

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(matrix[1,2])

6


In [ ]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
result = matrix * 2

In [ ]:
print(result)

[[ 2  4  6]
 [ 8 10 12]]


# Broadcasting

In [ ]:
result2 = matrix + 10

In [ ]:
print(result2)

[[11 12 13]
 [14 15 16]]


# Universal Functions

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
squared = np.square(arr1)

In [ ]:
squared

array([ 1,  4,  9, 16, 25, 36])

# Vectorization

# Efficient Memory Management

# Linear Algebra Operations