<a href="https://colab.research.google.com/github/cromcruach52/Pandas-Numpy-References/blob/main/NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np


# The Basics


In [14]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [15]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)


[[9. 8. 7.]
 [6. 5. 4.]]


In [16]:
# Get Dimension
b.ndim

2

In [17]:
# Get Shape
b.shape

(2, 3)

In [18]:
# Get Type
a.dtype

dtype('int16')

In [21]:
# Get Size
a.itemsize
b.itemsize

8

In [20]:
# Get total size
a.nbytes

6

# Accesing/Changing specific elements, rows, columns, etc

In [22]:
a1 = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# Get a specific element [r, c]
a1[1, 5]

13

In [30]:
# Get a specific row
a1[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
a1[:, 0]

array([1, 8])

In [33]:
# Get [startindex:endindex:stepsize]
a1[0, 1:6:2]


array([2, 4, 6])

In [37]:
# Replacing an element
a1[1,5] = 20
print(a1)

a1[:,2] = [1,2]
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [40]:
#3d Example

b1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
# Get specific element (work outside in)
b1[0,1,1]

b1[:,1,1]

array([4, 8])

In [49]:
# replace
b1[:,1,:] = [[9,9],[8,8]]
b1

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [53]:
#  All 0s matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# All 1s matrix

np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# Any other number

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [56]:
# Any other number (full_like)
np.full_like(a1, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [58]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.31196399, 0.04680987],
       [0.29371856, 0.49131151],
       [0.60069018, 0.18121823],
       [0.17891432, 0.04531974]])

In [61]:
# Random integer values
np.random.randint(3,7, size=(3,3))

array([[6, 6, 5],
       [3, 3, 6],
       [3, 6, 5]])

In [63]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
# Repeat an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [85]:
# Exercise

ex1 = np.ones((5,5))
print(ex1)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

ex1[1:4,1:4] = z
print(ex1)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [89]:
# Copying - Be Careful

a = np.array([1,2,3])

b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [90]:
b

array([100,   2,   3])

# Mathematics

In [91]:
a2 = np.array([1,2,3,4])
print(a2)

[1 2 3 4]


In [92]:
a2 + 2


array([3, 4, 5, 6])

In [93]:
a2 - 2

array([-1,  0,  1,  2])

In [94]:
a2 * 2

array([2, 4, 6, 8])

In [95]:
a2 / 2

array([0.5, 1. , 1.5, 2. ])

In [98]:
b2 = np.array([1,0,1,0])
a2 + b2

array([2, 2, 4, 4])

In [99]:
a2 ** 2

array([ 1,  4,  9, 16])

In [100]:
# Take the sin
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [103]:
# Linear Algebra

a3 = np.ones((2,3))
print(a3)

b3 = np.full((3,2), 2)
print(b3)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [106]:
# Matrix Multiplication

np.matmul(a3,b3)

array([[6., 6.],
       [6., 6.]])

In [107]:
# Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [108]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.min(stats)

1

In [110]:
np.max(stats)

6

In [113]:
np.sum(stats, axis = 0)

array([5, 7, 9])

# Reorganizing Arrays

In [117]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [118]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [120]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [121]:
# Load Data from File

# filedata = np.genfromtxt('data.txt', delimeter=',')
# filedata.astype('int32')
# filedata = filedata.astype('int32')